export const questions = [
    {
      id: 0,
      ques: "Drop full name here",
      description:
        "Please enter your full name.",
      placeholder: "John Doe",
      isOptional: false,
      regex: /^[a-zA-Z\s'-]+$/ ,
      err: "Full Name must contain only letters, spaces, hyphens, and apostrophes.",
    },
    {
      id: 1,
      ques: "Your LinkedIn URL",
      description:
        "Add your LinkedIn URL",
        isOptional: false,
      placeholder: "https://www.linkedin.com/in/johndoe",
      regex: /https:\/\/www\.linkedin\.com\/in\/[a-zA-Z0-9-]+/ ,
      err: "Hmm..Linkedin is missing",
    },
    {
      id: 2,
      ques: "Your Work Email Address",
      description:
        "Add your email below to get notified as soon as it is available.",
      placeholder: "johndoe@gmail.com",
      isOptional: false,
      regex: /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/ ,
      err: "Please enter a valid email address (e.g., user@example.com).",
    },
    {
        id: 3,
        ques: "Where do you work?",
        description:
          "Tell us about your work",
        placeholder: "YC",
        isOptional: true,
      },
    {
      id: 4,
      ques: "What industries are you interested in working?",
      description:
        "Tell us about your industries",
      placeholder: "B2B, AI, Gaming",
      isOptional: false,
      options: [
        "Sector Agnostic",
        "B2B",
        "B2C",
        "AI/ML",
        "ΑΡΙ",
        "AR/VR",
        "Creator Economy",
        "Gaming",
        "Analytics",
        "Robotics",
        "Saas",
        "SpaceTech",
        "SportsTech",
        "Telecommunications",
        "Travel and Tourism",
        "Wearables",
        "Insurtech",
        "Agtech",
        "Automation",
        "BioTech",
        "Cloud",
        "Consumer Tech",
        "Crypto/Blockchain",
        "D2C",
        "DeepTech",
        "Developer Tools",
        "Media and Entertainment",
        "Mobility and Transportation",
        "PropTech",
        "Healthtech",
        "Legal tech",
        "Logistics and Supply Chain",
        "Manufacturing",
        "E-Commerce",
        "Education",
        "Climate Tech",
        "Fintech",
        "IoT",
        "Clean Energy",
        "Foodtech",
        "HRtech",
        "B2B Marketplace",
        "others",
        "E-sports",
        "MarTech",
        "MedTech",
        "Retail Tech",
        "others",
      ],
      err: "Atleast one option must be selected",
    },
    {
      id: 5,
      ques: "Your Area Of Expertise",
      description:
        "Expertise",
      placeholder: "yup yup",
     
 
      isOptional: true,
      options: [
        "Marketing",
        "Finance & Fundraising",
        "GTM",
        "Human resources",
        "Business strategy",
        "Legal & Compliance",
        "Human resources",
        "International expansion",
        "Network & Partnerships",
        "Product development",
        "Sales Network",
        "Engineering",
        "Customer success",
        "Research & Market analysis",
      ],
    },
    {
      id: 6,
      ques: "Your preferred cheque size",
      range: true,
    
      description:
        "How much would you like to invest?",
      placeholder: "$10000-$25000",
    //   regex: /^[a-zA-Z\s'-]+$/ ,
      isOptional: false,
      err: "Please indicate the range of your typical investments (e.g., $10,000 to $50,000).”",
    },
    
    {
      id: 7,
      ques: "Do you invest via angel syndicates?",
      isOptional: true,
      description:
        "angel syndicates?",
      placeholder: "Yes",
      selectYesOrNo: true,
      err: "Please indicate whether you invest via Angel Syndicates by selecting 'Yes' or 'No'."
    },
    {
      id: 8,
      ques: "Your porfolio companies",
      isOptional: false,
      description:
        "Add your email below to get notified as soon as it is available.",
      placeholder: "yup yup",
      regex: /^[^,]+,[^,]+,[^,]+/ ,
      err: "Please mention at least three portfolio companies, separated by commas.",
    },
    {
      id: 9,
      ques: "Upload your pic",
      upload: true,
      isOptional: true,
      description:
        "Add your email below to get notified as soon as it is available.",
      placeholder: "Your image",
      regex: /^.+\.(jpg|jpeg|png)$/ ,
      err: "Please upload a picture in .jpg, .jpeg, or .png format, not exceeding 5MB in size.",
    },
  ];